version: "3.9"

services:
  nuxt:
    container_name: nuxt
    build: docker/nuxt
    volumes:
      - ./front:/app:cached
      - nuxt_node_modules:/app/node_modules
    ports:
      - "80:3000"
      - "24678:24678"
      - "5555:5555"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
    # 初期構築段階ではコメントアウトする
    command: sh -c "yarn && yarn dev"
volumes:
  nuxt_node_modules:
